### ISSUE TITLE
cpsam output is flipped/rotated

### ISSUE THREAD

**Issue by romainGuiet** [MouseLand/cellpose#1174]
HI @carsen-stringer , Hi cellpose team,

Congratulation for the new version ! 🥳 

I just encountered a very weird issue , please see more below!

Best

R

**Describe the bug**
output looks flipped/rotated 

**To Reproduce**

I used a [biop-desktop](https://biop.github.io/biop-desktop-doc/) docker image, available on [dockerhub](https://hub.docker.com/repository/docker/biop/biop-cellpose/general) (version biop-cellpose:4.0.2)

using the command : 

```
python -Xutf8 -W ignore -m cellpose --dir path/to/image/--pretrained_model cpsam --save_tif --no_npy --use_gpu --verbose
```
it returns :  

| input |  cpsam ouput | 
| --- | --- | 
| ![Image](https://github.com/user-attachments/assets/86ce022d-d07c-4a9a-98d1-bb21b8402b87) | ![Image](https://github.com/user-attachments/assets/aac4cd8d-3366-4e9e-bf01-b7c4d75cb6d3) | 

Because it looks flipped and rotated, I applyied a "horizontal flip" + "90° rotation"  which gets me the "expected" output :

| input |  cpsam ouput + "horizontal flip" + "90° rotation" | 
| --- | --- | 
| ![Image](https://github.com/user-attachments/assets/86ce022d-d07c-4a9a-98d1-bb21b8402b87) | ![Image](https://github.com/user-attachments/assets/7dd953e6-2617-4522-bdc7-6a7d8eff6732) | 

**Run log**

```
 Cellpose2D: Welcome to CellposeSAM, cellpose v4.0.1! The neural network component of
 Cellpose2D: CPSAM is much larger than in previous versions and CPU excution is slow. 
 Cellpose2D: We encourage users to use GPU/MPS if available. 
 Cellpose2D: 
 Cellpose2D: 
 Cellpose2D: 2025-05-14 14:41:54,852 [INFO] WRITING LOG OUTPUT TO /home/biop/.cellpose/run.log
 Cellpose2D: 2025-05-14 14:41:54,852 [INFO] 
 Cellpose2D: cellpose version: 	4.0.2 
 Cellpose2D: platform:       	linux 
 Cellpose2D: python version: 	3.10.17 
 Cellpose2D: torch version:  	2.7.0+cu126
 Cellpose2D: 2025-05-14 14:41:55,191 [INFO] ** TORCH CUDA version installed and working. **
 Cellpose2D: 2025-05-14 14:41:55,192 [INFO] >>>> using GPU (CUDA)
 Cellpose2D: 2025-05-14 14:41:55,192 [WARNING] the '--no_resample' flag is deprecated in v4.0.1+ and no longer used
 Cellpose2D: 2025-05-14 14:41:55,192 [WARNING] the '--diam_mean' flag is deprecated in v4.0.1+ and no longer used
 Cellpose2D: 2025-05-14 14:41:55,268 [INFO] >>>> running cellpose on 1 images using all channels
 Cellpose2D: 2025-05-14 14:41:58,171 [INFO] >>>> loading model /home/biop/.cellpose/models/cpsam
 Cellpose2D: 2025-05-14 14:41:59,127 [INFO] 0%|          | 0/1 [00:00<?, ?it/s]
 Cellpose2D: 2025-05-14 14:42:00,153 [INFO] 100%|##########| 1/1 [00:01<00:00,  1.03s/it]
 Cellpose2D: 2025-05-14 14:42:00,154 [INFO] 100%|##########| 1/1 [00:01<00:00,  1.03s/it]
 Cellpose2D: 2025-05-14 14:42:00,154 [INFO] >>>> completed in 4.962 sec
```
